---
- name: motd for system memory usage
  hosts: servera
  become: yes

  tasks:
  - name: template for motd
    template:
      src: templates/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644

      
  