---
- name: user creations
  hosts: web
  become: yes
  vars_files: 
    - vars/users_vars.yml

  tasks:
    - name: add webadmin gruoup
      group:
        name: webadmin
        state: present

    - name: create users
      user:
        name: "{{ item.username }}"
        groups: "webadmin"
        state: present
      loop: "{{ users }}"

    - name: add authorized_keys
      authorized_key:
        user: "{{ item.username }}"
        key: "{{ lookup('file', 'files/' + item.username + '.key.pub') }}"
      loop: "{{ users }}"

    - name: Modify sudo config to allow webadmin users sudo without a password
      lineinfile:
        dest: "/etc/sudoers"
        state: present
        regexp: "^%webadmin"
        line: "%webadmin ALL=(ALL) NOPASSWD: ALL"

    - name: Ensure that the root user is not permitted to log in using SSH directly
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
      notify: restart sshd

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted    

