# This play book creates a passwordless SSH for the clients which you need to have... 

---
- name: Deploy public key to managed hosts - Ansible
  hosts: all

  tasks:
    - name: Key to be available in ~/.ssh/authorized_keys
      authorized_keys: 
        user: user
        state: present
        key: '{{ item }}'
      with_file:
        - ~/ssh/id_rsa.pub
