---
- name: create users
  hosts: servera
  become: yes
  become_user: root
  
  tasks:
  - name: Creating user1 [ first task ] 
    user:
      name: user1
      uid: 4000
      state: absent

  - name: Creating user2 [ second task ]
    user:
      name: user2
      uid: 4001
      state: absent

      