---
# creating a project for webserver
- name: project webserver
  hosts: web
  become: yes
  vars:
    - firewall_pkg: firewalld
    - web_pkg: httpd
    - web_svc: httpd
    - ssl_pkg: mod_ssl
    - python_pkg: python-passlib
    - httpdconf_src: files/httpd.conf
    - httpdconf_file: /etc/httpd/conf/httpd.conf
    - htaccess_src: files/.htaccess
    - secrets_dir: /etc/httpd/secrets
    - secrets_file: "{{ secrets_dir }}/htpasswd"
    - web_root: /var/www/html
    - web_user: guest
  
  vars_files:
    - vars/secret.yml

  tasks:
    - name: package installation
      yum:
        name:
          - "{{ firewall_pkg }}"
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
          - "{{ python_pkg }}"
        state: latest
    
    - name: copy httpd conf file
      copy:
        src: "{{ httpdconf_src }}"
        dest: "{{ httpdconf_file }}"
        owner: root
        group: root
        mode: 0644

    - name: create file
      file:
        state: directory
        path: "{{ secrets_dir }}"
        owner: apache
        group: apache
        mode: 0500
    
    - name: add .htpasswd module
      htpasswd:
        path: "{{ secrets_file }}"
        name: "{{ web_user }}"
        password: "{{ web_pass }}"
        owner: apache
        group: apache
        mode: 0400

    - name: copy .htaccess to remote
      copy:
        src: "{{ htaccess_src }}"
        dest: "{{ web_root }}/.htaccess"
        owner: apache
        group: apache
        mode: 0400
    
    - name: create index.html
      copy:
        dest: "{{ web_root }}/index.html"
        content: "{{ ansible_facts['fqdn'] }} ({{ ansible_facts['default_ipv4'] ['address'] }}) has been customized by Ansible.\n"

    - name: add httpd service to firewalld
      firewalld:
        service: https
        state: enabled
        permanent: true
        immediate: true

    - name: webservice enabled and restarted
      service:
        name: "{{ web_svc }}"
        state: restarted
        enabled: true

    - name: firewalld enabled and restarted
      service:
        name: firewalld
        state: restarted
        enabled: true

    
