---
- name: at module
  hosts: web
  become: yes

  tasks:
  - name: Create date and time file
    at:
      command: "date > /root/my_at_date_time"
      count: 1
      units: minutes
      unique: yes
      state: present