---
# tasks file for myfirewall
- name: install firewalld
  yum:
    name: firewalld
    state: latest

- name: start firewalld service
  service:
    name: firewalld
    state: started

- name: open firealld port
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: yes
  loop: "{{ firewall_services }}"

