---
- name: installing packages
  hosts: servera
  remote_user: vagrant
  become_method: sudo 
  become: yes
  
  tasks:
    - name: Install latest httpd
      yum:
        name: 
          - httpd
          - firewalld
        state: latest
            
    - name: start httpd service
      service:
        name: httpd
        state: started
        enabled: true

    - name: start firewalld service
      service:
        name: firewalld
        state: stopped
    
    - name: create default html for webserver
      copy:
        content: 'Welcome to example.com Intranet !'
        dest: /var/www/html/index.html 

- name: Website load check
  hosts: localhost
  become: no
  tasks:
    - name: check for URL status code
      uri:
        url: http://servera
        status_code: 200