---
# SELinix context for a file
- name: Using the file module to ensure SELinux file context
  hosts: web
  become: yes

  tasks:
   - name: SELinux file context is set to defaults
     file:
      path: /home/vagrant/users.txt
      seuser: _default
      serole: _default
      setype: _default
      selevel: _default
