---
- name: project-review
  hosts: servera,serverb
  become: yes
  serial: 1

  tasks:
    - name: import tasks for install httpd
      import_tasks: tasks/web_tasks.yml

    - name: import firewall task
      import_tasks: tasks/firewall_tasks.yml

  handlers:
  - name: restart_httpd
    service:
      name: httpd
      state: restarted
