---
# this can be used while performing patching in rolling update

- name: confiuring parall
  hosts: web
  serial: 2
  become: yes

  tasks:
  - name: install httpd
    yum: 
      name: httpd
      state: latest
    notify: restart_httpd
  
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted

