---
- name: install firewalld
  yum:
    name: firewalld
    state: latest

- name: firewalld service start
  service:
    name: firewalld
    state: started
    enabled: true

- name: open firewall port
  firewalld:
    service: http
    permanent: true
    immediate: yes
    state: enabled

  