---
# Defined the vairables externall and is being read from the files

- name: play using defining vars externally
  hosts: web
  vars_files: 
    - vars/users.yml
  become: yes

  tasks:
  - name: create users
    user:
      name: "{{ user }}"
      home: "{{ homedir }}" 
      state: absent
