---
#  vairables being defined in *host_vars* which are server specific and other related to groups are being defined in *group_vars*

- name: install httpd and user from host_vars
  hosts: servera  # you can change the same to group when group_vars are being defined
  become: yes

  tasks:
    - name: install httpd
      yum:
        name: "{{ package }}"
        state: present
    
    - name: user create
      user:
        name: "{{ user }}"
        state: present